name: Run tests

on:
  pull_request:
    branches:
      - main
  push:

jobs:
  run-tests:
    strategy:
      matrix:
        python-version: [3.12]

    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: python3 -m pip install -r requirements.txt

      - name: Show files
        run: ls interview_app/

      - name: Run tests
        run: python3 manage.py test